# Generated by Django 5.0 on 2024-02-10 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datetime_edite',
            new_name='datetime_edit',
        ),
    ]
